// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtZJdbt8cv56e_JLcGY0ycjlcS7lpk4u4',
    appId: '1:524427255355:web:61d66b923416dd64eb461e',
    messagingSenderId: '524427255355',
    projectId: 'xpanse-c0dd3',
    authDomain: 'xpanse-c0dd3.firebaseapp.com',
    storageBucket: 'xpanse-c0dd3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOlgOJPfCQBj0G8H0yz98ARy2MWhhk9kc',
    appId: '1:524427255355:android:ab76cbcc3471855feb461e',
    messagingSenderId: '524427255355',
    projectId: 'xpanse-c0dd3',
    storageBucket: 'xpanse-c0dd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbcP75dxs6FIZ6Mv7h_Jl5qvi8_bBtLIQ',
    appId: '1:524427255355:ios:fbe861574c1f4019eb461e',
    messagingSenderId: '524427255355',
    projectId: 'xpanse-c0dd3',
    storageBucket: 'xpanse-c0dd3.firebasestorage.app',
    iosBundleId: 'com.example.expencetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbcP75dxs6FIZ6Mv7h_Jl5qvi8_bBtLIQ',
    appId: '1:524427255355:ios:fbe861574c1f4019eb461e',
    messagingSenderId: '524427255355',
    projectId: 'xpanse-c0dd3',
    storageBucket: 'xpanse-c0dd3.firebasestorage.app',
    iosBundleId: 'com.example.expencetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtZJdbt8cv56e_JLcGY0ycjlcS7lpk4u4',
    appId: '1:524427255355:web:3894e87e208609a1eb461e',
    messagingSenderId: '524427255355',
    projectId: 'xpanse-c0dd3',
    authDomain: 'xpanse-c0dd3.firebaseapp.com',
    storageBucket: 'xpanse-c0dd3.firebasestorage.app',
  );
}
